# Demonstração Pré-Processamento de Dados
### Disciplina - Introdução a Ciência de Dados - Univesp
### Videoaula 12
### Prof. Dr. José Eduardo Santarem Segundo
Aluno: Luiz Henrique Rodrigues Ferreira
## notebookComAnotaçõesDaVideoaula

O pré-processamento é uma fase que antecede ao uso dos modelos
de machine learning que veremos adiante, entretanto para que ele
possa ser executado com clareza e também com assertividade é de
fundamental importância que se conheça o processo completo de um
projeto de DS

# Importar Bibliotecas

In [14]:
import pandas as pd

# Trabalhar com dados dos jogos de Tenis como exemplo.
### https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2021.csv

Download de base de dados da internet.
Criando dataframe com as informações dos jogos de tênis.

In [2]:
dados=pd.read_csv('https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2021.csv')

Mostrando as 5 primeiras(head(5)) linhas do dataframe.

In [3]:
dados.head(5)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0


Imprima um resumo conciso de um DataFrame.

Este método imprime informações sobre um DataFrame incluindo o índice dtype e colunas, valores não nulos e uso de memória.

In [4]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2733 entries, 0 to 2732
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   tourney_id          2733 non-null   object 
 1   tourney_name        2733 non-null   object 
 2   surface             2733 non-null   object 
 3   draw_size           2733 non-null   int64  
 4   tourney_level       2733 non-null   object 
 5   tourney_date        2733 non-null   int64  
 6   match_num           2733 non-null   int64  
 7   winner_id           2733 non-null   int64  
 8   winner_seed         1165 non-null   float64
 9   winner_entry        417 non-null    object 
 10  winner_name         2733 non-null   object 
 11  winner_hand         2733 non-null   object 
 12  winner_ht           2731 non-null   float64
 13  winner_ioc          2733 non-null   object 
 14  winner_age          2733 non-null   float64
 15  loser_id            2733 non-null   int64  
 16  loser_

Gerando estatísticas descritivas.

As estatísticas descritivas incluem aquelas que resumem a tendência central, a dispersão e a forma da distribuição de um conjunto de dados, excluindo os NaNvalores.

Analisa séries numéricas e de objetos, bem como DataFrame conjuntos de colunas de tipos de dados mistos. A saída irá variar dependendo do que é fornecido. Consulte as notas abaixo para obter mais detalhes

In [5]:
dados.describe(include='all')

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
count,2733,2733,2733,2733.000000,2733,2.733000e+03,2733.000000,2733.000000,1165.000000,417,...,2636.000000,2636.000000,2636.000000,2637.000000,2636.000000,2636.000000,2729.000000,2729.000000,2707.000000,2707.000000
unique,114,114,3,NaN,5,NaN,NaN,NaN,NaN,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-540,Wimbledon,Hard,NaN,A,NaN,NaN,NaN,NaN,Q,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,127,127,1608,NaN,1569,NaN,NaN,NaN,NaN,234,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,62.609587,NaN,2.021060e+07,243.248811,127500.755946,7.687554,NaN,...,50.118361,33.325493,14.494689,12.420554,4.843323,8.714719,70.593624,2229.913888,103.034355,1390.971555
std,NaN,NaN,NaN,41.521804,NaN,2.855522e+02,73.915192,33930.996942,7.133621,NaN,...,19.075552,14.205041,6.857036,4.224477,3.253624,4.126347,103.028379,2484.822372,149.125316,1460.007475
min,NaN,NaN,NaN,2.000000,NaN,2.021010e+07,1.000000,100644.000000,1.000000,NaN,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,NaN,NaN,NaN,32.000000,NaN,2.021032e+07,224.000000,105575.000000,3.000000,NaN,...,36.000000,23.000000,10.000000,9.000000,2.000000,6.000000,19.000000,858.000000,37.000000,709.000000
50%,NaN,NaN,NaN,64.000000,NaN,2.021061e+07,276.000000,106432.000000,6.000000,NaN,...,47.000000,31.000000,14.000000,11.000000,4.000000,8.000000,47.000000,1344.000000,68.000000,993.000000
75%,NaN,NaN,NaN,128.000000,NaN,2.021082e+07,289.000000,128034.000000,10.000000,NaN,...,61.000000,42.000000,18.000000,15.000000,7.000000,11.000000,87.000000,2423.000000,112.000000,1595.000000


Detectando valores ausentes.

Retorna um objeto booleano de mesmo tamanho indicando se os valores são NA. Valores NA, como Nenhum ou numpy.NaN, são mapeados para valores verdadeiros. Todo o resto é mapeado para valores falsos. Caracteres como strings vazias ''ou numpy.infnão são considerados valores NA (a menos que você defina ).pandas.options.mode.use_inf_as_na = True

In [6]:
dados.isnull()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
1,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
2,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
4,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
2729,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
2730,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
2731,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False


### Verificar valores nulos nas colunas. Somando os valores nulos de cada coluna.

In [7]:
dados.isnull().sum()

,0
tourney_id,0
tourney_name,0
surface,0
draw_size,0
tourney_level,0
tourney_date,0
match_num,0
winner_id,0
winner_seed,1568
winner_entry,2316


### Verificar coluna "winner_entry", que tem muitos valores nulos e indica como o vencedor entrou no torneio

In [8]:
dados['winner_entry'].describe()

,winner_entry
count,417
unique,6
top,Q
freq,234


In [9]:
dados['winner_entry'].unique()

array([nan, 'Q', 'WC', 'LL', 'SE', 'Alt', 'PR'], dtype=object)

### Apagar todas as linhas que o atributo "loser_rank" é nulo, porque são poucas ocasiões e isso pode implicar erros nos resultados.

In [10]:
dados.dropna(subset=['loser_rank'], inplace=True)

In [11]:
dados

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,2021-9210,Laver Cup,Hard,8,A,20210924,102,126610,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,5173.0,11.0,3368.0
2729,2021-9210,Laver Cup,Hard,8,A,20210924,103,106421,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10575.0,12.0,3310.0
2730,2021-9210,Laver Cup,Hard,8,A,20210924,104,126094,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6130.0,15.0,2800.0
2731,2021-9210,Laver Cup,Hard,8,A,20210924,105,100644,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,7760.0,22.0,2171.0


### Apagar colunas que todos os valores são nulos

In [12]:
dados.dropna(axis=1, how= 'all')

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,2021-9210,Laver Cup,Hard,8,A,20210924,102,126610,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,5173.0,11.0,3368.0
2729,2021-9210,Laver Cup,Hard,8,A,20210924,103,106421,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10575.0,12.0,3310.0
2730,2021-9210,Laver Cup,Hard,8,A,20210924,104,126094,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6130.0,15.0,2800.0
2731,2021-9210,Laver Cup,Hard,8,A,20210924,105,100644,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,7760.0,22.0,2171.0


### Alterar valor dos dados nulos em uma coluna

In [13]:
dados['loser_entry'].unique()

array([nan, 'PR', 'Q', 'LL', 'WC', 'SE', 'Alt'], dtype=object)

In [14]:
dados['loser_entry'].fillna(value='X',inplace=True)

/tmp/ipykernel_719/2380784803.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dados['loser_entry'].fillna(value='X',inplace=True)


In [15]:
dados['loser_entry'].unique()

array(['X', 'PR', 'Q', 'LL', 'WC', 'SE', 'Alt'], dtype=object)

### Alterar mais de um atributo, com condições diferentes

In [16]:
dados['w_ace'].unique()

array([nan,  5.,  1.,  2.,  3.,  6.,  4., 11.,  8., 15.,  9., 20., 12.,
       24., 14., 17., 13., 19., 10.,  7., 16., 18., 22.,  0., 23., 21.,
       32., 26., 25., 27., 28., 29., 41., 34., 30., 44., 33., 49., 31.,
       36.])

In [17]:
dados['loser_ht'].unique()

array([180., 183., 185., 193., 191., 173., 170., 188., 178., 196., 198.,
       175., 181., 211., 208., 201., 190., 203.,  nan, 189.,  15.])

Trecho de código abaixo vamos substituir os valores da coluna  w_ace = 0 pela média dos valores dessa coluna.

In [18]:
dados.fillna(value={'w_ace':0,'loser_ht':dados['loser_ht'].mean()},inplace=True)

In [19]:
dados['w_ace'].unique()

array([ 0.,  5.,  1.,  2.,  3.,  6.,  4., 11.,  8., 15.,  9., 20., 12.,
       24., 14., 17., 13., 19., 10.,  7., 16., 18., 22., 23., 21., 32.,
       26., 25., 27., 28., 29., 41., 34., 30., 44., 33., 49., 31., 36.])

In [20]:
dados['loser_ht'].unique()

array([180.        , 183.        , 185.        , 193.        ,
       191.        , 173.        , 170.        , 188.        ,
       178.        , 196.        , 198.        , 175.        ,
       181.        , 211.        , 208.        , 201.        ,
       190.        , 203.        , 186.73409763, 189.        ,
        15.        ])

### Usar o método ffill para projetar um dado para o registro seguinte

Sinônimo de DataFrame.fillna()com method='ffill'.
Devoluções
Series / DataFrame ou Nenhum
Objeto com valores ausentes preenchidos ou Nenhum se inplace=True.

Método ffill para projetar um dado para o registro seguinte, ou seja, eu pego um dado que está nulo. Pegar o dado do registro anterior e coloco nele. As vezes é um dados de uma série temporal.

Método ffill  vai substituir o valor NaN do ano 1984 e substituir pelo valor anterior(1983). o mesmo vai acontecer com valor de 1988.

In [21]:
dados['minutes'][1975:1990]

,minutes
1978,67.0
1979,129.0
1980,91.0
1981,140.0
1982,83.0
1983,74.0
1984,90.0
1985,71.0
1986,124.0
1987,140.0


In [24]:
dados['minutes'].fillna(method='ffill',inplace=True)

/tmp/ipykernel_719/3114364062.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dados['minutes'].fillna(method='ffill',inplace=True)
/tmp/ipykernel_719/3114364062.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dados['minutes'].fillna(method='ffill',inplace=True)


In [23]:
dados['minutes'][1975:1990]

,minutes
1978,67.0
1979,129.0
1980,91.0
1981,140.0
1982,83.0
1983,74.0
1984,90.0
1985,71.0
1986,124.0
1987,140.0


### Identificar duplicados

In [25]:
dados.duplicated()

,0
0,False
1,False
2,False
3,False
4,False
...,...
2728,False
2729,False
2730,False
2731,False


In [26]:
dados.duplicated().sum()

np.int64(0)

### Eliminar duplicados de uma coluna (nem sempre se quer realmente fazer isso, cuidado)

In [27]:
dados.drop_duplicates(subset=['tourney_name'],inplace=True)

In [ ]:
dados['tourney_name'].head(10)

0               Delray Beach
27                   Antalya
58     Great Ocean Road Open
113        Murray River Open
168                  Atp Cup
198          Australian Open
325                  Cordoba
352                Singapore
379              Montpellier
406             Buenos Aires
Name: tourney_name, dtype: object

In [28]:
dados.describe()

,draw_size,tourney_date,match_num,winner_id,winner_seed,winner_ht,winner_age,loser_id,loser_seed,loser_ht,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
count,110.000000,1.100000e+02,110.000000,110.000000,11.000000,109.000000,110.000000,110.000000,2.000000,110.000000,...,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,109.000000,109.000000,110.000000,110.000000
mean,28.272727,2.021077e+07,147.463636,132444.963636,2.636364,186.155963,26.620909,127675.763636,7.500000,186.131529,...,46.113208,29.518868,12.481132,10.933962,4.462264,8.141509,130.963303,1659.550459,206.081818,774.890909
std,31.388045,3.299224e+02,127.788578,35819.636900,2.540580,5.927298,4.900966,36480.909687,0.707107,6.804056,...,19.663028,13.125933,5.926906,3.002440,3.604691,4.681145,167.072003,2475.617400,276.922608,722.899353
min,2.000000,2.021010e+07,1.000000,100644.000000,1.000000,170.000000,17.800000,103852.000000,7.000000,170.000000,...,16.000000,5.000000,2.000000,4.000000,0.000000,1.000000,1.000000,7.000000,5.000000,1.000000
25%,4.000000,2.021050e+07,1.000000,105606.250000,1.000000,183.000000,23.550000,105526.000000,7.250000,183.000000,...,33.250000,20.250000,8.000000,9.000000,2.000000,5.000000,42.000000,477.000000,67.000000,238.000000
50%,32.000000,2.021092e+07,239.000000,124940.500000,2.000000,185.000000,25.100000,106165.500000,7.500000,185.000000,...,42.500000,27.000000,12.500000,10.000000,4.000000,7.500000,95.000000,811.000000,101.500000,780.000000
75%,32.000000,2.021111e+07,271.000000,136022.500000,2.000000,191.000000,29.525000,130971.750000,7.750000,191.000000,...,56.000000,37.000000,16.000000,13.000000,6.000000,11.000000,155.000000,1492.000000,251.750000,999.000000
max,128.000000,2.021120e+07,286.000000,209867.000000,9.000000,201.000000,40.100000,208502.000000,8.000000,211.000000,...,165.000000,90.000000,32.000000,18.000000,27.000000,38.000000,1165.000000,12113.000000,1921.000000,5150.000000


# Vamos ver como fazer um deslocamento
### Vamos importar os dados das ações da Apple
### https://finance.yahoo.com/quote/AAPL/history/

In [ ]:
dados2=pd.read_csv("AAPL.csv")
# Deixando comentado que, após um update, não é mais possível baixar dados do Yahoo Finance sem ter uma Gold Subscription!

FileNotFoundError: [Errno 2] No such file or directory: 'AAPL.csv'

In [ ]:
dados2

In [ ]:
dados2['close_ontem']=dados2['Close'].shift(1)

In [ ]:
dados2

###Nova coluna com a porcentagem de alteração de um dia para o outro

In [ ]:
dados2['alteracao %']=((dados2['Close']/dados2['close_ontem'])-1)*100

In [ ]:
dados2.head(20)

In [ ]:
dados2.dropna(subset=['alteracao %'], inplace=True)

In [ ]:
dados2

In [ ]:
dados2.describe(include = 'all')

###Transformar dados categóricos (qualitativos) em dados numéricos

In [ ]:
dados=pd.read_csv('https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2021.csv')

In [ ]:
dados['winner_ioc']

In [ ]:
dados['winner_ioc'].unique()

###Veja a documentação do scikit-learn sobre preprocessing!!!!

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
paises=dados['winner_ioc']

In [ ]:
paises

In [ ]:
lencoder = LabelEncoder()
paises_numeros = lencoder.fit_transform(paises)
paises_numeros

In [ ]:
paises.head(10)

In [ ]:
dados['paises_numeros']=paises_numeros

In [ ]:
dados